//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlProj.Utils.Dac.Merge {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DacMergeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DacMergeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlProj.Utils.Dac.Merge.DacMergeResource", typeof(DacMergeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Backup:{0}.
        /// </summary>
        internal static string BackupArg {
            get {
                return ResourceManager.GetString("BackupArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating checksum.
        /// </summary>
        internal static string CalculatingChecksum {
            get {
                return ResourceManager.GetString("CalculatingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying streams in to target package.
        /// </summary>
        internal static string CopyingStreams {
            get {
                return ResourceManager.GetString("CopyingStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: directory not found [{0}].
        /// </summary>
        internal static string ErrorDirNotFound {
            get {
                return ResourceManager.GetString("ErrorDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: file not found [{0}].
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: input and output file are identical.
        /// </summary>
        internal static string ErrorInputEqualToOutput {
            get {
                return ResourceManager.GetString("ErrorInputEqualToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: invalid parameter [{0}].
        /// </summary>
        internal static string ErrorInvalidParameter {
            get {
                return ResourceManager.GetString("ErrorInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no input filename specified.
        /// </summary>
        internal static string ErrorNoInputFile {
            get {
                return ResourceManager.GetString("ErrorNoInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no output filename specified.
        /// </summary>
        internal static string ErrorNoOutputfile {
            get {
                return ResourceManager.GetString("ErrorNoOutputfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: the input file is not a valid DACPAC.
        /// </summary>
        internal static string ErrorNotValidDacPac {
            get {
                return ResourceManager.GetString("ErrorNotValidDacPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: output file {0} already exists.
        /// </summary>
        internal static string ErrorOutputFileExists {
            get {
                return ResourceManager.GetString("ErrorOutputFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: invalid action [{0}].
        /// </summary>
        internal static string ErrorUnknownAction {
            get {
                return ResourceManager.GetString("ErrorUnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /InputFilename:{0}.
        /// </summary>
        internal static string InputFileNameArg {
            get {
                return ResourceManager.GetString("InputFileNameArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}.
        /// </summary>
        internal static string LoadingFile {
            get {
                return ResourceManager.GetString("LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging {0}.
        /// </summary>
        internal static string MergeFile {
            get {
                return ResourceManager.GetString("MergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging model elements ({0}).
        /// </summary>
        internal static string MergeModelElements {
            get {
                return ResourceManager.GetString("MergeModelElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New checksum [{0}].
        /// </summary>
        internal static string NewChecksum {
            get {
                return ResourceManager.GetString("NewChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /OutputFilename:{0}.
        /// </summary>
        internal static string OutputFileNameArg {
            get {
                return ResourceManager.GetString("OutputFileNameArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Overwrite:{0}.
        /// </summary>
        internal static string OverwriteArg {
            get {
                return ResourceManager.GetString("OverwriteArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ReferenceLoadPath:{0}.
        /// </summary>
        internal static string RelativeLoadPathArg {
            get {
                return ResourceManager.GetString("RelativeLoadPathArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0} of {1} ({2}).
        /// </summary>
        internal static string RemoveDescendents {
            get {
                return ResourceManager.GetString("RemoveDescendents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0} ({1}).
        /// </summary>
        internal static string RemovingElements {
            get {
                return ResourceManager.GetString("RemovingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing attached annotations.
        /// </summary>
        internal static string StatusRemovinAttachedAnnotations {
            get {
                return ResourceManager.GetString("StatusRemovinAttachedAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing annotations.
        /// </summary>
        internal static string StatusRemovingAnnotations {
            get {
                return ResourceManager.GetString("StatusRemovingAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing headers.
        /// </summary>
        internal static string StatusRemovingHeaders {
            get {
                return ResourceManager.GetString("StatusRemovingHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream {0}.
        /// </summary>
        internal static string Stream {
            get {
                return ResourceManager.GetString("Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating input file inplace [{0}].
        /// </summary>
        internal static string UpdateInplace {
            get {
                return ResourceManager.GetString("UpdateInplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating checksum.
        /// </summary>
        internal static string UpdatingChecksum {
            get {
                return ResourceManager.GetString("UpdatingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing model stream.
        /// </summary>
        internal static string WritingModelStream {
            get {
                return ResourceManager.GetString("WritingModelStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing origin stream.
        /// </summary>
        internal static string WritingOriginStream {
            get {
                return ResourceManager.GetString("WritingOriginStream", resourceCulture);
            }
        }
    }
}
