//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlProj.Utils.Dac.Checksum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DacChkSumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DacChkSumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlProj.Utils.Dac.Checksum.DacChkSumResource", typeof(DacChkSumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating checksum.
        /// </summary>
        internal static string CalculatingChecksum {
            get {
                return ResourceManager.GetString("CalculatingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: file [{0}] not found.
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: input and output file are identical.
        /// </summary>
        internal static string ErrorInputEqualToOutput {
            get {
                return ResourceManager.GetString("ErrorInputEqualToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: invalid parameter [{0}].
        /// </summary>
        internal static string ErrorInvalidParameter {
            get {
                return ResourceManager.GetString("ErrorInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no input filename specified.
        /// </summary>
        internal static string ErrorNoInputFile {
            get {
                return ResourceManager.GetString("ErrorNoInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no output filename specified.
        /// </summary>
        internal static string ErrorNoOutputfile {
            get {
                return ResourceManager.GetString("ErrorNoOutputfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: the input file is not a valid DACPAC.
        /// </summary>
        internal static string ErrorNotValidDacPac {
            get {
                return ResourceManager.GetString("ErrorNotValidDacPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: output file {0} already exists.
        /// </summary>
        internal static string ErrorOutputFileExists {
            get {
                return ResourceManager.GetString("ErrorOutputFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: invalid action [{0}].
        /// </summary>
        internal static string ErrorUnknownAction {
            get {
                return ResourceManager.GetString("ErrorUnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing attached annotations.
        /// </summary>
        internal static string StatusRemovinAttachedAnnotations {
            get {
                return ResourceManager.GetString("StatusRemovinAttachedAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing annotations.
        /// </summary>
        internal static string StatusRemovingAnnotations {
            get {
                return ResourceManager.GetString("StatusRemovingAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing headers.
        /// </summary>
        internal static string StatusRemovingHeaders {
            get {
                return ResourceManager.GetString("StatusRemovingHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing model stream.
        /// </summary>
        internal static string WritingModelStream {
            get {
                return ResourceManager.GetString("WritingModelStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing origin stream.
        /// </summary>
        internal static string WritingOriginStream {
            get {
                return ResourceManager.GetString("WritingOriginStream", resourceCulture);
            }
        }
    }
}
